- name: Configure mysql
  hosts: mysql
  become: yes

  tasks:
  - name: Install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: Install PyMySQL dependency
    ansible.builtin.dnf:
      name: python3-PyMySQL
      state: present

  - name: Enable and start mysql-server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true


  - name: set mysql root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1



